
server:
  port: 8080

spring:
  application:
    name: spring-ai-multiple-llms

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
          temperature: 0.7